CREATE TABLE IF NOT EXISTS standardMetrics (
    prefix VARCHAR,
    cik INTEGER,
    accessionNumber VARCHAR,
    form VARCHAR,
    endDate DATE,
    units VARCHAR,
    "Revenue" DOUBLE,
    "Cost of Revenue" DOUBLE,
    "Gross Profit" DOUBLE,
    "Research and Development Expenses" DOUBLE,
    "Selling, General and Administrative Expenses" DOUBLE,
    "Operating Expenses" DOUBLE,
    "Operating Income" DOUBLE,
    "Interest Expense" DOUBLE,
    "Interest Income" DOUBLE,
    "Pre-tax Income" DOUBLE,
    "Income Tax Expense" DOUBLE,
    "Net Income" DOUBLE,
    "Cash and Cash Equivalents" DOUBLE,
    "Accounts Receivable" DOUBLE,
    "Inventory" DOUBLE,
    "Total Current Assets" DOUBLE,
    "Property, Plant and Equipment, Net" DOUBLE,
    "Goodwill" DOUBLE,
    "Intangible Assets" DOUBLE,
    "Total Assets" DOUBLE,
    "Accounts Payable" DOUBLE,
    "Short-term Borrowings" DOUBLE,
    "Current Portion of Long-term Debt" DOUBLE,
    "Deferred Revenue" DOUBLE,
    "Total Current Liabilities" DOUBLE,
    "Long-term Debt" DOUBLE,
    "Total Debt" DOUBLE,
    "Total Liabilities" DOUBLE,
    "Retained Earnings" DOUBLE,
    "Total Equity" DOUBLE,
    "Operating Cash Flow" DOUBLE,
    "Depreciation and Amortization" DOUBLE,
    "Stock-based Compensation" DOUBLE,
    "Capital Expenditures" DOUBLE,
    "Dividends Paid" DOUBLE
);
CHECKPOINT;